import type { Metadata } from "next";
import Footer from "./(dashboard)/footer/page";
import "./globals.css";

export const metadata: Metadata = {
  title: "Social Wave",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="h-full">
      <body className={`flex flex-col min-h-screen`}>
        <div>{children}</div>
      </body>
    </html>
  );
}
