import type { Metadata } from "next";
// import Header from "./Header/page";
// import Footer from "./Footer/page";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="h-full">
      <body className={`flex flex-col h-screen`}>
        {/* <Header /> */}
        <main className="flex-1 overflow-y-scroll">{children}</main>
        {/* <Footer /> */}
      </body>
    </html>
  );
}
