import type { Metadata } from "next";
import Header from "./header/page";
import Footer from "./footer/page";
import "./globals.css";

export const metadata: Metadata = {
  title: "Social Wave",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="h-full">
      <body className={`flex flex-col h-screen`}>
        <Header />
        <main className="flex-1 overflow-y-scroll">{children}</main>
        <Footer />
      </body>
    </html>
  );
}
